# Site settings
title: Missing Brackets
email: tiagodksp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An aspiring web developer's blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
#twitter_username: 
github_username:  tiagojmartins

# Build settings
markdown: kramdown
