# Site settings
title: Missing Brackets
email: tiagodksp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Rants and thoughts about an aspiring web developer's journey.
baseurl: "" # the subpath of the jekyll genererated website
url: "" # the base hostname & protocol for the website
#twitter_username: #register twitter missingbrackets
github_username:  tiagojmartins

# Build settings
markdown: kramdown
